import type { Metadata } from 'next'
import { Lato } from 'next/font/google'
import './globals.css'
import MainLayout from '@/components/Layouts/MainLayout/MainLayout'

const lato = Lato({ subsets: ['latin'], weight: ['300', '400', '700', '900'], variable: '--var-lato' })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={lato.className}>
        <MainLayout>{children}</MainLayout>
      </body>
    </html>
  )
}
