export const enum COLOR {
    DarkGreen = '#264504',
    Green = '#007300',
    Salad = '#71BE1E',
    Cherry = '#7A0210',
    Red = '#E5021E',
    Salmon = '#FD1A36',
    Blue = '#185499',
    LightBlue = '#64A0E6',
    Brown = '#8B572A',
    Orange = '#F19A0B',
    Yellow = '#F7BD5B',
    Purple = '#9D2EFE',
    Turquoise = '#22D7AE',
    Pink = '#D132F1',
    Gray = '#656565',
}

export const colorSchema: readonly COLOR[] = [
    COLOR.DarkGreen,
    COLOR.Green,
    COLOR.Salad,
    COLOR.Cherry,
    COLOR.Red,
    COLOR.Salmon,
    COLOR.Blue,
    COLOR.Turquoise,
    COLOR.LightBlue,
    COLOR.Brown,
    COLOR.Orange,
    COLOR.Yellow,
    COLOR.Purple,
    COLOR.Pink,
    COLOR.Gray,
];

